### ISSUE TITLE
Sherpa cannot find rivetAnalysis

### ISSUE THREAD

**Issue by kdilsiz** [davidchall/homebrew-hep#103]
Dear Experts,

I am tried to install Sherpa-2.1.1 on my computer and lxplus. However, I encountered the error below when I did "make" after configuration. Could you please help me fix this?
Thanks in advance,
Kamuran 

fatal error: too many errors emitted, stopping now [-ferror-limit=]
22 warnings and 20 errors generated.
make[3]: *** [libSherpaRivetAnalysis_la-Rivet_Interface.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by davidchall** [comment]
Are you installing Sherpa using homebrew-hep? Or are you installing this manually? It is not clear from your post.

**Comment by davidchall** [comment]
Closing due to lack of details.

**Comment by sumaniiti** [comment]
Hi, I have similar error as follows,
fatal error: too many errors emitted, stopping now [-ferror-limit=]
22 warnings and 20 errors generated.
make[2]: *** [libSherpaRivetAnalysis_la-Rivet_Interface.lo] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

And I am installing without using homebrew-hep on Macbook OS. Could you please help me fix this?
