### ISSUE TITLE
Sacrifice Install for Pythia8 Failed

### ISSUE THREAD

**Issue by shomiller** [davidchall/homebrew-hep#104]
Dear Experts,

After successfully installing pythia8 using homebrew-hep, it was recommended that I run "brew install sacrifice" as the easiest way to generate Pythia8 events. Unfortunately, upon doing make install, this resulted in an error that I'm having trouble interpreting. The resulting output is copied below. Any help would be greatly appreciated.

Thanks,
Sam

"
==> ./configure --prefix=/usr/local/Cellar/sacrifice/1.0.0 --with-pythia=/usr/lo
==> make install
Last 15 lines from /Users/shomiller/Library/Logs/Homebrew/sacrifice/02.make:
clang++ -DHAVE_CONFIG_H -I. -I../config  -Wall -O2 -I../ -I../include -I/usr/local/include -I/usr/local/opt/pythia8/include/ -DPYTHIA8200 -DENABLE__BINRELOC -DDEFAULTDATADIR=\"/usr/local/opt/pythia8/share/Pythia8/xmldoc\" -DDEFAULTPARAMDIR=\"/usr/local/Cellar/sacrifice/1.0.0/share/Sacrifice\" -DDEFAULTLIBDIR=\"/usr/local/Cellar/sacrifice/1.0.0/lib\" -I/usr/local/include/ -DHEPMC_HAS_UNITS -DHAS_HEPMC -I/private/tmp/sacrifice-20170705-90344-s0tnlu/Sacrifice-1.0.0/include/ -DHAS_MCUTILS -I/usr/local/Cellar/lhapdf/6.1.6/include -I/usr/local/opt/boost/include   -Wall -O2 -g -O2 -c -o run_pythia-BeamParticle.o `test -f 'BeamParticle.cxx' || echo './'`BeamParticle.cxx
clang++ -DHAVE_CONFIG_H -I. -I../config  -Wall -O2 -I../ -I../include -I/usr/local/include -I/usr/local/opt/pythia8/include/ -DPYTHIA8200 -DENABLE__BINRELOC -DDEFAULTDATADIR=\"/usr/local/opt/pythia8/share/Pythia8/xmldoc\" -DDEFAULTPARAMDIR=\"/usr/local/Cellar/sacrifice/1.0.0/share/Sacrifice\" -DDEFAULTLIBDIR=\"/usr/local/Cellar/sacrifice/1.0.0/lib\" -I/usr/local/include/ -DHEPMC_HAS_UNITS -DHAS_HEPMC -I/private/tmp/sacrifice-20170705-90344-s0tnlu/Sacrifice-1.0.0/include/ -DHAS_MCUTILS -I/usr/local/Cellar/lhapdf/6.1.6/include -I/usr/local/opt/boost/include   -Wall -O2 -g -O2 -c -o run_pythia-UserHooksFactory.o `test -f 'UserHooksFactory.cxx' || echo './'`UserHooksFactory.cxx
clang++ -DHAVE_CONFIG_H -I. -I../config  -Wall -O2 -I../ -I../include -I/usr/local/include -I/usr/local/opt/pythia8/include/ -DPYTHIA8200 -DENABLE__BINRELOC -DDEFAULTDATADIR=\"/usr/local/opt/pythia8/share/Pythia8/xmldoc\" -DDEFAULTPARAMDIR=\"/usr/local/Cellar/sacrifice/1.0.0/share/Sacrifice\" -DDEFAULTLIBDIR=\"/usr/local/Cellar/sacrifice/1.0.0/lib\" -I/usr/local/include/ -DHEPMC_HAS_UNITS -DHAS_HEPMC -I/private/tmp/sacrifice-20170705-90344-s0tnlu/Sacrifice-1.0.0/include/ -DHAS_MCUTILS -I/usr/local/Cellar/lhapdf/6.1.6/include -I/usr/local/opt/boost/include   -Wall -O2 -g -O2 -c -o run_pythia-PythiaMain.o `test -f 'PythiaMain.cxx' || echo './'`PythiaMain.cxx
clang++ -DHAVE_CONFIG_H -I. -I../config  -Wall -O2 -I../ -I../include -I/usr/local/include -I/usr/local/opt/pythia8/include/ -DPYTHIA8200 -DENABLE__BINRELOC -DDEFAULTDATADIR=\"/usr/local/opt/pythia8/share/Pythia8/xmldoc\" -DDEFAULTPARAMDIR=\"/usr/local/Cellar/sacrifice/1.0.0/share/Sacrifice\" -DDEFAULTLIBDIR=\"/usr/local/Cellar/sacrifice/1.0.0/lib\" -I/usr/local/include/ -DHEPMC_HAS_UNITS -DHAS_HEPMC -I/private/tmp/sacrifice-20170705-90344-s0tnlu/Sacrifice-1.0.0/include/ -DHAS_MCUTILS -I/usr/local/Cellar/lhapdf/6.1.6/include -I/usr/local/opt/boost/include   -Wall -O2 -g -O2 -c -o run_pythia-MCUtilsHandler_enabled.o `test -f 'MCUtilsHandler_enabled.cxx' || echo './'`MCUtilsHandler_enabled.cxx
clang++ -DHAVE_CONFIG_H -I. -I../config  -Wall -O2 -I../ -I../include -I/usr/local/include -I/usr/local/opt/pythia8/include/ -DPYTHIA8200 -DENABLE__BINRELOC -DDEFAULTDATADIR=\"/usr/local/opt/pythia8/share/Pythia8/xmldoc\" -DDEFAULTPARAMDIR=\"/usr/local/Cellar/sacrifice/1.0.0/share/Sacrifice\" -DDEFAULTLIBDIR=\"/usr/local/Cellar/sacrifice/1.0.0/lib\" -I/usr/local/include/ -DHEPMC_HAS_UNITS -DHAS_HEPMC -I/private/tmp/sacrifice-20170705-90344-s0tnlu/Sacrifice-1.0.0/include/ -DHAS_MCUTILS -I/usr/local/Cellar/lhapdf/6.1.6/include -I/usr/local/opt/boost/include   -Wall -O2 -g -O2 -c -o run_pythia-PhotosHandler_disabled.o `test -f 'PhotosHandler_disabled.cxx' || echo './'`PhotosHandler_disabled.cxx
clang++ -DHAVE_CONFIG_H -I. -I../config  -Wall -O2 -I../ -I../include -I/usr/local/include -I/usr/local/opt/pythia8/include/ -DPYTHIA8200 -DENABLE__BINRELOC -DDEFAULTDATADIR=\"/usr/local/opt/pythia8/share/Pythia8/xmldoc\" -DDEFAULTPARAMDIR=\"/usr/local/Cellar/sacrifice/1.0.0/share/Sacrifice\" -DDEFAULTLIBDIR=\"/usr/local/Cellar/sacrifice/1.0.0/lib\" -I/usr/local/include/ -DHEPMC_HAS_UNITS -DHAS_HEPMC -I/private/tmp/sacrifice-20170705-90344-s0tnlu/Sacrifice-1.0.0/include/ -DHAS_MCUTILS -I/usr/local/Cellar/lhapdf/6.1.6/include -I/usr/local/opt/boost/include   -Wall -O2 -g -O2 -c -o run_pythia-HepMCIOHandler_no_gzip.o `test -f 'HepMCIOHandler_no_gzip.cxx' || echo './'`HepMCIOHandler_no_gzip.cxx
clang -DHAVE_CONFIG_H -I. -I../config  -Wall -O2 -I../ -I../include -I/usr/local/include -I/usr/local/opt/pythia8/include/ -DPYTHIA8200 -DENABLE__BINRELOC -DDEFAULTDATADIR=\"/usr/local/opt/pythia8/share/Pythia8/xmldoc\" -DDEFAULTPARAMDIR=\"/usr/local/Cellar/sacrifice/1.0.0/share/Sacrifice\" -DDEFAULTLIBDIR=\"/usr/local/Cellar/sacrifice/1.0.0/lib\" -I/usr/local/include/ -DHEPMC_HAS_UNITS -DHAS_HEPMC -I/private/tmp/sacrifice-20170705-90344-s0tnlu/Sacrifice-1.0.0/include/ -DHAS_MCUTILS -I/usr/local/Cellar/lhapdf/6.1.6/include -I/usr/local/opt/boost/include    -g -O2 -c -o run_pythia-binreloc.o `test -f 'binreloc.c' || echo './'`binreloc.c
PythiaMain.cxx:99:17: error: no member named 'set_crash_on_problem' in 'HepMC::Pythia8ToHepMC'
  pythiaToHepMC.set_crash_on_problem(true);
  ~~~~~~~~~~~~~ ^
1 error generated.
make[2]: *** [run_pythia-PythiaMain.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
"

**Comment by davidchall** [comment]
Hi Sam,

Unfortunately, Sacrifice has not kept up-to-date with changes to Pythia8. I think the latest version that it was updated for was Pythia8.200.

You can see the commit history for Sacrifice here: https://agile.hepforge.org/trac/log/contrib/Sacrifice
and a ChangeLog here: https://agile.hepforge.org/trac/browser/contrib/Sacrifice/ChangeLog

If the install fails, this would be my first guess as to why. We should remove the caveat from the Pythia8 formula, so it stops recommending Sacrifice. If you must use Sacrifice, you should try using an earlier version of Pythia8.

**Comment by davidchall** [comment]
I've removed the `sacrifice` formula since it has not kept up-to-date with `pythia`.
