### ISSUE TITLE
Problem with lhapdf installation

### ISSUE THREAD

**Issue by ragheedalhyder** [davidchall/homebrew-hep#105]
Hello,

Following exactly the instruction to install lhapdf in order to install Superchic, I have always this problem : 
Traceback (most recent call last):
  File "./lhapdf", line 12, in <module>
    __version__ = lhapdf.__version__
AttributeError: 'module' object has no attribute '__version__'

When I try to run ./lhapdf install MMHT2014lo68cl in the bin folder. I am not an expert user in these problems but it seems that I cannot get rid of this error whatever I do.

**Comment by ebothmann** [comment]
It seems that your `lhapdf` script that lives in your `.` directory does not match the `lhapdf` python library it loads (which probably knows about `lhapdf.__version__`, but not `lhapdf.version`, I suspect the latter is an outdated way to access the version). So somehow your set-up is inconsistent. You should inspect your `$PATH` and your `$PYTHON_PATH` environment variables and make sure that both point first to the binaries and python libraries that homebrew has installed for `lhapdf`. Then do `lhapdf install MMHT2014lo68cl`. If all that does not help, maybe `brew doctor` does?

**Comment by marinang** [comment]
I don't know if it is linked to this problem but I cannot download/install lhapdf6.

**Comment by marinang** [comment]
Today I can download but there is a new problem during the building

Already downloaded: /Users/matthieumarinangeli/Library/Caches/Homebrew/lhapdf-6.1.6.tar.gz
==> ./configure --prefix=/usr/local/Cellar/lhapdf/6.1.6 --with-boost=/usr/local/opt/boost
==> make
Last 15 lines from /Users/matthieumarinangeli/Library/Logs/Homebrew/lhapdf/02.make:
running install
running build
running build_ext
building 'lhapdf' extension
creating build
creating build/temp.macosx-10.12-x86_64-2.7
clang -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/private/tmp/lhapdf-20170719-1709-1fgmqco/LHAPDF-6.1.6/include -I/private/tmp/lhapdf-20170719-1709-1fgmqco/LHAPDF-6.1.6/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c lhapdf.cpp -o build/temp.macosx-10.12-x86_64-2.7/lhapdf.o -I/usr/local/opt/boost/include -I/usr/local/Cellar/lhapdf/6.1.6/include
lhapdf.cpp:4:10: fatal error: 'Python.h' file not found
#include "Python.h"
         ^
1 error generated.
error: command 'clang' failed with exit status 1
make[2]: *** [all-local] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

**Comment by ebothmann** [comment]
Hi, maybe you have to redo `xcode-select --install`. Is `brew doctor` maybe telling you some warnings? In principle you could `brew install python`, but in principle it should work with the system python as well. I'm not sure why the header is missing. - eno

**Comment by ragheedalhyder** [comment]
Try linking the lhapdf library correctly:

`brew link lhapdf`

If that does not work, try:

`brew link --overwrite lhapdf`

**Comment by ebothmann** [comment]
I don't think that this will solve the problem, `Python.h` is a python header, not an `lhapdf` header.

However, also my tip `xcode-select --install` won't help. In fact, looking at your log we see that it is looking for a brew-install python header. If you do `ls /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7`, you should see there a header with the name `Python.h`. If not (and apparently it is not found when compiling), you might have to reinstall python using homebrew, i.e. `brew reinstall python` or maybe just `brew link python`.
