### ISSUE TITLE
Download failed for madgraph 

### ISSUE THREAD

**Issue by marinang** [davidchall/homebrew-hep#106]
Hi,

 brew install madgraph5_amcatnlo
==> Installing madgraph5_amcatnlo from davidchall/hep
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://launchpad.net/mg5amcnlo/2.0/2.5.x/+download/MG5_aMC_v2.5.2.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "madgraph5_amcatnlo"
Download failed: https://launchpad.net/mg5amcnlo/2.0/2.5.x/+download/MG5_aMC_v2.5.2.tar.gz

**Comment by ebothmann** [comment]
Apparently the MadGraph people have removed/replaced their older release version download links. You can `brew edit madgraph5_amcatnlo` and put in the correct download link. If you update the formula, don't forget to submit a [Pull Request](https://help.github.com/articles/about-pull-requests/). Cheers, eno

**Comment by davidchall** [comment]
Fixed by #107
