### ISSUE TITLE
brew update reports: "Warning: Calling 'depends_on :fortran' is deprecated!" and others

### ISSUE THREAD

**Issue by haggerty** [davidchall/homebrew-hep#119]
Hello,

Thanks for maintaining these packages, it's a very useful service to the HEP community.

I don't think these are serious errors, but since they repeat themselves on every brew update and say to report them, here it is.

### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [think so] Checked that a similar issue hasn't already been filed?
- [?] Looked up the software bug tracker if reporting a build error?
- [not relevant] If you're seeing permission errors, tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:

brew update reports deprecated directives in formula, as far as I can see.

#### The complete command that you issued:

[~]$ brew update
Updated 1 tap (homebrew/core).
==> Updated Formulae
iron-functions                                    owfs                                              sslh
Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/davidchall/homebrew-hep/Formula/mcfm.rb:11:in `<class:Mcfm>'
Please report this to the davidchall/hep tap!

Warning: Calling 'depends_on :mpi' is deprecated!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/davidchall/homebrew-hep/Formula/sherpa.rb:30:in `<class:Sherpa>'
Please report this to the davidchall/hep tap!

Warning: Calling 'depends_on :python3' is deprecated!
Use 'depends_on "python3"' instead.
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:88:in `parse_spec'

Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:88:in `parse_spec'

#### Gist with output of `brew doctor`:

Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/davidchall/homebrew-hep/Formula/mcfm.rb:11:in `<class:Mcfm>'
Please report this to the davidchall/hep tap!

Warning: Calling 'depends_on :mpi' is deprecated!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/davidchall/homebrew-hep/Formula/sherpa.rb:30:in `<class:Sherpa>'
Please report this to the davidchall/hep tap!

Warning: Calling 'depends_on :python3' is deprecated!
Use 'depends_on "python3"' instead.
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:88:in `parse_spec'

Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:88:in `parse_spec'

#### Link output by `brew gist-logs <formula>`:

[~]$ brew gist-logs mcfm
Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/davidchall/homebrew-hep/Formula/mcfm.rb:11:in `<class:Mcfm>'
Please report this to the davidchall/hep tap!

Error: No logs.

#### Output of `brew config`:

[~]$ brew config
HOMEBREW_VERSION: 1.5.0
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 985202cf8e3f9e221753dd99adf1e8874fece03a
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d4d15a8268f85582195d6aa185fda5f2207e0c41
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 9.0.4, 1.6.0_65-b14-468
macOS: 10.13.2-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11

**Comment by davidchall** [comment]
I think I fixed these warnings in the latest commit https://github.com/davidchall/homebrew-hep/commit/2b682e388be24650bab4e21e837adb2bd612c0d3. 

Please let me know if this resolves your issue.

**Comment by haggerty** [comment]
I reinstalled mcfm and sherpa, and I agree, the warnings are gone.  Thanks!
