### ISSUE TITLE
homebrew-hep on formulae.brew.sh

### ISSUE THREAD

**Issue by koraktor** [davidchall/homebrew-hep#133]
Since a long time your tap repository has been around and has been listed on [formulae.brew.sh](formulae.brew.sh) (formerly braumeister.org). So thanks for your contribution to Homebrew’s ecosystem.

Recently, Homebrew has chosen to integrate and deprecate all of its own tap repositories, like e.g. homebrew-php which has been deprecated as the last one a few days ago.

Now, homebrew-hep is the last tap repository to be listed on formulae.brew.sh and I’d like to remove it too. I’ll use this issue to give you some time to adapt your repository (README and web page links to braumeister.org) and maybe you want to discuss the removal.

There are two reasons for the removal of homebrew-hep:

 * To our users it might not be clearly visible that this tap is not part of Homebrew and is not supported by Homebrew’s maintainers.
 * Given it’s the last tap, I’d be able to remove a lot of code that has been put in place to support multiple tap repositories.

Thanks and sorry for any inconvenience.

**Comment by davidchall** [comment]
Thanks for letting me know - and thanks for hosting the list of `homebrew-hep` packages for all this time! I've updated our README.
