### ISSUE TITLE
getting topdrawer on the Mac (problem with deprecated repositories)

### ISSUE THREAD

**Issue by hehaber** [davidchall/homebrew-hep#134]
In trying to install topdrawer, there is a problem with the dependencies.  One is homebrew/x11/imake.  However, the repository  homebrew/x11 has been deprecated and imake now appears in homebrew/core.  More problematical is homebrew/head-only/f2c.  It seems that f2c is nowhere to be found.  In fact, homebrew/head-only is deprecated and f2c was moved a few years ago to homebrew/boneyard.  But now homebrew/boneyard is deprecated, and f2c seems to have disappeared entirely.

Topdrawer also needs ugs.  One of its dependencies is homebrew/x11/imake, which has already been mentioned above that imake has been moved to homebrew/core. 

Is it possible to update topdrawer so that it can be installed on a new mac using homebrew?

**Comment by ebothmann** [comment]
The dependency issues should now be solved after merging #146. However, there are still compilation errors when I try to `brew install topdrawer` on my machine. I had similar errors with other homebrew-hep formulae that went away after updating the formula version, so I guess it has something to do with updated macOS/xCode compilers/toolchain ... unfortunately I couldn't find a fixed topdrawer source with a quick search (and I'm not a user, so I'm not super motivated to follow up on this right now).

**Comment by davidchall** [comment]
Should be fixed by #207
