### ISSUE TITLE
Rivet: EOS.undent is disabled

### ISSUE THREAD

**Issue by QuantumKnoll26** [davidchall/homebrew-hep#135]
Troubleshooting steps taken:

- Ran `brew update` and retried your prior step?
- Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- Checked that a similar issue hasn't already been filed?

#### Brief summary of issue:
Instalingl rivet fails at last step. Got the following output: (all other steps completed successfully )

==> Pouring rivet-2.5.4.high_sierra.bottle.tar.gz
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/davidchall/homebrew-hep/Formula/rivet.rb:64:in `caveats'
Please report this to the davidchall/hep tap!
Or, even better, submit a PR to fix it!

**Comment by cverhaaren** [comment]
Similar issue in madgraph:
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/davidchall/homebrew-hep/Formula/madgraph5_amcatnlo.rb:36:in `caveats'
Please report this to the davidchall/hep tap!
Or, even better, submit a PR to fix it!

**Comment by ebothmann** [comment]
This issue has been addressed by #146. Thanks for flagging this!
