### ISSUE TITLE
LHAPDF Installation Error

### ISSUE THREAD

**Issue by JesseKent** [davidchall/homebrew-hep#137]
### Indicate troubleshooting steps taken

- [ Yes] Ran `brew update` and retried your prior step?
- [Yes ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [Yes ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [Not Allowed ] If you're seeing permission errors, tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
Unable to install or get info on LHAPDF

#### The complete command that you issued:
brew info lhapdf

#### Gist with output of `brew doctor`:
Error: Calling <<-EOS.undent is disabled!
/usr/local/Homebrew/Library/Taps/davidchall/homebrew-hep/Formula/lhapdf.rb:49:in `caveats'
Please report this to the davidchall/hep tap!

#### Link output by `brew gist-logs <formula>`:
https://gist.github.com/a51d67d67b2a61fd9491405ed8ab770e

#### Output of `brew config`:
HOMEBREW_VERSION: 1.6.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: c814199a791867ab75f90a22715e2475706b13d8
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7b09734b500baec2e588fe12834c237295d03fee
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.15.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.5-x86_64
CLT: 9.4.1.0.1.1528165917

**Comment by ebothmann** [comment]
This issue has been addressed by #146. Thanks for flagging this!
