### ISSUE TITLE
madgraph5_amcatnlo

### ISSUE THREAD

**Issue by sabahsalih** [davidchall/homebrew-hep#138]
brew install madgraph5_amcatnlo

I keep getting
Updating Homebrew...
==> Installing madgraph5_amcatnlo from davidchall/hep
==> Downloading https://launchpad.net/mg5amcnlo/2.0/2.6.x/+download/MG5_aMC_v2.6.0.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "madgraph5_amcatnlo"
Download failed: https://launchpad.net/mg5amcnlo/2.0/2.6.x/+download/MG5_aMC_v2.6.0.tar.gz

If I type
https://launchpad.net/mg5amcnlo/2.0/2.6.x/+download/MG5_aMC_v2.6.3.2.tar.gz

in the browser it work.

How I could get brew to download from
https://launchpad.net/mg5amcnlo/2.0/2.6.x/+download/MG5_aMC_v2.6.3.2.tar.gz

Many Thanks, Sabah.

**Comment by ebothmann** [comment]
This issue has been addressed by #146. Thanks for flagging this!
