### ISSUE TITLE
fastNLO running issue

### ISSUE THREAD

**Issue by xwang-rs** [davidchall/homebrew-hep#139]
#### Brief summary of issue:
I installed fastNLO via homebrew-hep successfully. However, when I run fnlo-tk-cppread, i.e. "fnlo-tk-cppread LHC13-173.3-Mtt.tab CT14nnlo_as_0118 1 LHAPDF no", it will get error like this:
ERROR!   [fastNLOCoeffAddFix::ReadCoeffAddBase] Only IPDFCoeffFormat==0 is implemented, but IPDFCoeffFormat=-1. Exiting.

Since the installation was smooth, I would not run brew doctor, etc. Does anyone know this running issue? Since I can run successfully on a Ubuntu.

Many thanks for any suggestions.

**Comment by davidchall** [comment]
This sounds like it might be an upstream issue. In any case, we should be looking at the latest version of fastnlo. Please see #216.
