### ISSUE TITLE
Sherpa installation fails; homebrew/science was deprecated

### ISSUE THREAD

**Issue by danchus** [davidchall/homebrew-hep#140]
### Indicate troubleshooting steps taken

- [x ] Ran `brew update` and retried your prior step?
- [x ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x ] Checked that a similar issue hasn't already been filed?

#### Brief summary of issue:
I am unable to install Sherpa. When I do the command
$ brew search sherpa

I get:
Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.

But I don't know to where it has migrated. When I do 
$ brew search sherpa
it does appear. 

Is it possible to see where it migrated to?

Thanks!
Daniel

#### Output of `brew config`:
$ brew config
HOMEBREW_VERSION: 1.7.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: d6a245c05110c240e680da594c2cc6038998b82e
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ae2c8d2f70f39f5f04f220330fd94a5094816483
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.15.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 9.4.0.0.1.1526532315
Xcode: 9.4.1
XQuartz: N/A

**Comment by ebothmann** [comment]
This issue has been addressed by #146. Thanks for flagging this!
