### ISSUE TITLE
root running issue after updating to macOS Mojave

### ISSUE THREAD

**Issue by xiaoniuniu** [davidchall/homebrew-hep#141]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors, tried running `sudo chown -R $(whoami) $(brew --prefix)`?

Hi all,

I'm a green-hand on this. After updating to macOS Mojave, root 6.14.04 has a running issue. I've reinstall homebrew and root, this issue is still there. It seems Mojave migrated some important files to somewhere else. The issue is:

`└─[$] root                                                                                                                          [11:02:48]
ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
  LC_ALL=C /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++   -O2 -DNDEBUG -xc++ -E -v /dev/null 2>&1 >/dev/null | awk '/^#include </,/^End of search/{if (!/^#include </ && !/^End of search/){ print }}' | GREP_OPTIONS= grep -E "(c|g)\+\+"
Results was:
With exit code 256
input_line_1:1:10: fatal error: 'new' file not found
#include <new>
         ^~~~~
input_line_3:37:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
   ------------------------------------------------------------
  | Welcome to ROOT 6.14/04                http://root.cern.ch |
  |                               (c) 1995-2018, The ROOT Team |
  | Built for macosx64                                         |
  | From tags/v6-14-04@v6-14-04, Aug 23 2018, 17:00:44         |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q' |
   ------------------------------------------------------------

input_line_9:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
root [0] 
`

There already is a discussion: [https://root-forum.cern.ch/t/root-stopped-working-after-macos-update-to-mojave/30845](url) , but I still don't know how to fix this.

Could anyone help on this?

**Comment by adavidzh** [comment]
1. I'm afraid that this repo is not the place to for this issue.
1. It seems that you have some `root` logon macros that may be the issue. What do you get for `root -n -b -q`?
1. Finally, it works for me:
```
[adavid:~] $ brew info root
root: stable 6.16.00 (bottled), HEAD
Object oriented framework for large scale data analysis
https://root.cern.ch/
/usr/local/Cellar/root/6.16.00 (5,382 files, 291MB) *
  Poured from bottle on 2019-03-14 at 18:00:44
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/root.rb
==> Dependencies
Build: cmake ✔
Required: davix ✔, fftw ✔, gcc ✔, graphviz ✔, gsl ✔, libxml2 ✔, lz4 ✔, openssl ✔, pcre ✔, python ✔, tbb ✔, xrootd ✔, xz ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Because ROOT depends on several installation-dependent
environment variables to function properly, you should
add the following commands to your shell initialization
script (.bashrc/.profile/etc.), or call them directly
before using ROOT.

For bash users:
  . /usr/local/bin/thisroot.sh
For zsh users:
  pushd /usr/local >/dev/null; . bin/thisroot.sh; popd >/dev/null
For csh/tcsh users:
  source /usr/local/bin/thisroot.csh

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/root
[adavid:~] 7s $ which root
/usr/local/Cellar/root/6.16.00/bin/root
[adavid:~] $ root -b -q
   ------------------------------------------------------------
  | Welcome to ROOT 6.16/00                  https://root.cern |
  |                               (c) 1995-2018, The ROOT Team |
  | Built for macosx64 on Jan 23 2019, 09:06:13                |
  | From tags/v6-16-00@v6-16-00                                |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q' |
   ------------------------------------------------------------


 Beginning new ROOT session

[adavid:~] $
```

**Comment by ebothmann** [comment]
Same here (although I don't get the "Beginning new ROOT session" line). Maybe @xiaoniuniu can re-try with the current ROOT formula. I'll close this issue.
