### ISSUE TITLE
Madgraph download error

### ISSUE THREAD

**Issue by xiaoniuniu** [davidchall/homebrew-hep#142]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors, tried running `sudo chown -R $(whoami) $(brew --prefix)`?

when installing the Madgraph, there is an error for downloading:

curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "madgraph5_amcatnlo"
Download failed: https://launchpad.net/mg5amcnlo/2.0/2.6.x/+download/MG5_aMC_v2.6.0.tar.gz

I guess there is an issue about the download link?

**Comment by ebothmann** [comment]
This issue has been addressed by #146. Thanks for flagging this!
