### ISSUE TITLE
Error: Calling needs :cxx11 is disabled! There is no replacement.

### ISSUE THREAD

**Issue by lntsmn** [davidchall/homebrew-hep#143]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors, tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Please complete the following:

Remove or fix `needs :cxx11` lines

#### Brief summary of issue:

Running `brew update` highlights that `needs :cxx11` is now disabled,
formulae that contain this line need updating.

**Comment by ebothmann** [comment]
This issue has been addressed by #146. Thanks for flagging this!
