### ISSUE TITLE
problem with Herwig installation

### ISSUE THREAD

**Issue by arthurmmoraes** [davidchall/homebrew-hep#153]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors, tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:

Unsuccessful installation of HERWIG through homebrew/hep (http://davidchall.github.io/homebrew-hep/#detailed-installation-instructions). 

Installation crashes almost at the end...problem seems to be related to missing lhapdf.
Tried to run lhapdf-install, but that also failed...there was also an error message associated to lhadpf. I suspect the problem is in lhapdf, which is a requisite to run Herwig.

Got this (towards the end):

==> make install
Last 15 lines from /Users/amoraes/Library/Logs/Homebrew/herwig/03.make:
  /bin/sh ../libtool   --mode=install /usr/bin/install -c Herwig '/usr/local/Cellar/herwig/7.1.2/bin'
 /usr/bin/install -c herwig-config '/usr/local/Cellar/herwig/7.1.2/bin'
 /usr/bin/install -c -m 644 DIS.in DIS-Matchbox.in GammaGamma.in ILC.in ILC-MSSM.in ILC-MUED.in ILC-RS.in LEP.in LEP-Matchbox.in LHC-ADD.in LHC-CEX.in LHC-GammaGamma.in LHC.in LHC-Matchbox.in LHC-LQ.in LHC-MSSM.in LHC-MUED.in LHC-NMSSM.in LHC-Powheg.in LHC-RPV.in LHC-RS.in LHC-Sextet.in LHC-TRP.in LHC-TTBA.in LHC-MB.in LHC-ZP.in TVT.in TVT-Powheg.in TVT-TTBA.in LHC-LH.in LHC-LHTP.in LHE.in CMSSM40.1.1.slha NMSSM.spc ADD.model Leptoquark.model LH.model LHTP.model MSSM.model MUED.model '/usr/local/Cellar/herwig/7.1.2/share/Herwig'
 /usr/bin/install -c -m 644 Makefile-UserModules '/usr/local/Cellar/herwig/7.1.2/share/Herwig'
 /usr/bin/install -c -m 644 NMSSM.model RPV-Bi.model RPV-Tri.model RS.model Sextet.model TTBA.model Zprime.model RPV-BI.slha RPV-TRI.slha RPV-UDD.slha '/usr/local/Cellar/herwig/7.1.2/share/Herwig'
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-data-hook
Creating repository
libtool: install: /usr/bin/install -c .libs/Herwig /usr/local/Cellar/herwig/7.1.2/bin/Herwig
Error: 'set /Herwig/Partons/HardLOPDF:PDFName MMHT2014lo68cl': PDF not installed. Try 'lhapdf install'.
make[5]: *** [install-data-hook] Error 1
make[4]: *** [install-data-am] Error 2
make[3]: *** [install-am] Error 2
make[2]: *** [install-recursive] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/davidchall/homebrew-hep/issues

#### The complete command that you issued:

After the usual update and doctor, I then used:
brew install herwig

#### Gist with output of `brew doctor`:
Arthurs-MacBook-Air:local amoraes$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /opt/local/bin/ncursesw6-config
  /opt/local/bin/ncurses6-config
Arthurs-MacBook-Air:local amoraes$ 

#### Output of `brew config`:
Arthurs-MacBook-Air:local amoraes$ brew config
HOMEBREW_VERSION: 2.1.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: aa043c1d678afd26f50156a83417c296cb9d5a4b
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e3905928c882addee5c19888e3ca5e0cb6e0ccb7
Core tap last commit: 49 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15-x86_64
CLT: 11.0.0.0.1.1567737322
Xcode: 11.1
CLT headers: 11.0.0.0.1.1567737322
Arthurs-MacBook-Air:local amoraes$

**Comment by ebothmann** [comment]
Hey @arthurmmoraes,

The bottled (i.e. pre-compiled) LHAPDF is broken (`lhapdf-install` does not work). This is patched if you install lhapdf from source (using `brew install -s lhapdf`). Try this before installing Herwig.

@davidchall Could we disable all bottles for the time being? I can't upgrade them due to permissions, see #147, also at the moment I would not volunteer to do it due to time reasons. However, since they are all outdated now we should probably not default to bottled installations.

**Comment by davidchall** [comment]
Hi @arthurmmoraes - I've resolved this issue in #201. Could you please try again?
