### ISSUE TITLE
could someone help upgrade pythia8 to lastest version 8243? now is 8230.

### ISSUE THREAD

**Issue by cxwx** [davidchall/homebrew-hep#154]
as the title

**Comment by cxwx** [comment]
is the project still active?

**Comment by ebothmann** [comment]
Hi @cxwx,

oh definitely. But we do not have the time (and interest) to keep everything up-to-date all the time. Please consider to update the package yourself and submit a pull request. It just involves changing two lines and checking that the installation still works. Some instructions can be found at the [homebrew-hep](http://davidchall.github.io/homebrew-hep/) site.

Cheers
 eno

**Comment by cxwx** [comment]
I've pull the request, but no one merge it to master version.
