### ISSUE TITLE
Problem with Sherpa Installation manually with RIVET interface

### ISSUE THREAD

**Issue by sumaniiti** [davidchall/homebrew-hep#158]
Hi, I have similar error as follows,
fatal error: too many errors emitted, stopping now [-ferror-limit=]
22 warnings and 20 errors generated.
make[2]: *** [libSherpaRivetAnalysis_la-Rivet_Interface.lo] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

And I am installing without using homebrew-hep on Macbook OS. Could you please help me fix this?

**Comment by sumaniiti** [comment]
Hi, Above problem solved by using CXXFLAGS="-std=c++11".
But now different error is displayed after Make Install as follows:
make[1]: *** [Sherpa.html] Error 1
make: *** [install-recursive] Error 1

Is it somethings serious?

**Comment by davidchall** [comment]
I'm afraid we don't provide support for installations outside of homebrew-hep. However, after #213 you can have achieve your goal using `brew install sherpa`.
