### ISSUE TITLE
whizard downloading package not found

### ISSUE THREAD

**Issue by DavidW99** [davidchall/homebrew-hep#164]
Hi, there

I think the URL link for WHIZARD and fastjet might need an update?

==> Downloading from https://whizard.hepforge.org/whizard-2.7.0.tar.gz
#=#=-#  #
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "whizard"
Download failed: http://whizard.hepforge.org/whizard-2.7.0.tar.gz

**Comment by DavidW99** [comment]
I updated the URL locally and assign new sha256, but I encounters this configuration error.

configure: error: could not compile kinds selection program.

**Comment by ebothmann** [comment]
Unfortunately, there is no expert we can ask to fix it. The original formula author is not actively contributing anymore. Hopefully you can find a fix. In that case, please follow up on this issue and submit a PR 👍

**Comment by davidchall** [comment]
I think this has been fixed by #196. Could you please try again?
