### ISSUE TITLE
Error installing Herwig on Big Sur MBP

### ISSUE THREAD

**Issue by ramc77** [davidchall/homebrew-hep#168]
I want to install Herwig on macOS (Big Sur) on MacBook Pro. But I get this error: 

MacBook-Pro:~ ramchand$ brew install herwig
Updating Homebrew...
==> Installing herwig from davidchall/hep
==> Downloading https://dl.bintray.com/davidchall/bottles-hep/thepeg-2.1.2.high_
#=#=-#  #                                                                     
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "thepeg"
Download failed: https://dl.bintray.com/davidchall/bottles-hep/thepeg-2.1.2.high_sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://www.hepforge.org/archive/thepeg/ThePEG-2.1.2.tar.bz2
==> Downloading from https://thepeg.hepforge.org/downloads?f=ThePEG-2.1.2.tar.bz
          -=O=#     #    #     #                                              
==> Downloading https://www.hepforge.org/archive/herwig/Herwig-7.1.2.tar.bz2
==> Downloading from https://herwig.hepforge.org/downloads?f=Herwig-7.1.2.tar.bz
                   -=O=-           #     #     #     #                        
==> Installing dependencies for davidchall/hep/herwig: thepeg
==> Installing davidchall/hep/herwig dependency: thepeg
==> Pouring thepeg-2.1.2.high_sierra.bottle.tar.gz
tar: Error opening archive: Failed to open '/Users/ramchand/Library/Caches/Homebrew/downloads/dd62dc554655900115a019f89f2e25efc588db99968458e4ef809b370640464c--thepeg-2.1.2.high_sierra.bottle.tar.gz'
Error: Failure while executing; `tar xof /Users/ramchand/Library/Caches/Homebrew/downloads/dd62dc554655900115a019f89f2e25efc588db99968458e4ef809b370640464c--thepeg-2.1.2.high_sierra.bottle.tar.gz -C /var/folders/4p/07zrcnn950vgpcfyn873s08w0000gn/T/d20201217-77715-7ksfth` exited with 1. Here's the output:
tar: Error opening archive: Failed to open '/Users/ramchand/Library/Caches/Homebrew/downloads/dd62dc554655900115a019f89f2e25efc588db99968458e4ef809b370640464c--thepeg-2.1.2.high_sierra.bottle.tar.gz'

Warning: Bottle installation failed: building from source.
==> ./configure --prefix=/usr/local/Cellar/thepeg/2.1.2 --enable-stdcxx11 --with
==> make
Last 15 lines from /Users/ramchand/Library/Logs/Homebrew/thepeg/02.make:
  CXX      HepMCAnalysis_la-HepMCFile.lo
  CXX      HepMCAnalysis_la-HIHepMCFile.lo
  CXX      GraphvizPlot.lo
  CXX      HepMCAnalysis_la-NLOHepMCFile.lo
  CXXLD    libThePEGHist.la
  CXXLD    ProgressLog.la
  CXXLD    XSecCheck.la
  CXXLD    GraphvizPlot.la
  CXXLD    LWHFactory.la
  CXXLD    HepMCAnalysis.la
  CXXLD    RivetAnalysis.la
ld: file not found: /usr/local/opt/gsl/lib/libgsl.23.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [RivetAnalysis.la] Error 1
make: *** [all-recursive] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/davidchall/homebrew-hep/issues

MacBook-Pro:~ ramchand$ 

Please help me, thank you very much!
Ram

**Comment by ebothmann** [comment]
Dear @ramc77,

I'm sorry, but for now homebrew-hep does not supported prebuilt binary installs (via "bottles" in homebrew-speak), cf. #147. Please re-try using `brew install -s ...` to install from source.

I tentatively close this issue, but feel free to re-open if this did not actually solve the problem.

I hope this helps!
 eno
