### ISSUE TITLE
lhapdf download failed

### ISSUE THREAD

**Issue by preimer** [davidchall/homebrew-hep#178]
### Indicate troubleshooting steps taken

- [x ] Ran `brew update` and retried your prior step?
- [x ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x ] Checked that a similar issue hasn't already been filed?
- [x ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors, tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
I attempted to install lhapdf and obtained the following errors:

`CSI358562:~ reimer$ brew install lhapdf
==> Installing lhapdf from davidchall/hep
==> Downloading https://dl.bintray.com/davidchall/bottles-hep/lhapdf-6.2.1.high_
##O#- #                                                                       
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "lhapdf"
Download failed: https://dl.bintray.com/davidchall/bottles-hep/lhapdf-6.2.1.high_sierra.bottle.tar.gz
CSI358562:~ reimer$ `

It appears to me to be on the server side given the http response

#### The complete command that you issued:
`brew install lhapdf`

#### Gist with output of `brew doctor`:
`CSI358562:~ reimer$ brew doctor
Your system is ready to brew.`

#### Link output by `brew gist-logs <formula>`:
`CSI358562:~ reimer$ brew gist-logs lhapdf
Error: No logs.`

#### Output of `brew config`:
`CSI358562:~ reimer$ ### brew config
HOMEBREW_VERSION: 3.2.2-49-g331fe33
ORIGIN: https://github.com/Homebrew/brew
HEAD: 331fe33e6db777d6711f35c7c3535796a59cd1b5
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ba6c484183dc18bab7058b75a9f99edb608eff46
Core tap last commit: 25 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.bUfoy9Aemg/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: 12.5.1
XQuartz: 2.7.11 => /opt/X11`

**Comment by ebothmann** [comment]
Hi @preimer 

The bottle (prebuilt binaries) support is broken in homebrew-hep. I've removed it in the latest commit on master, so if you brew-update, you can re-try and it should work.

I'm tentatively closing this issue, assuming it's resolved. Feel free to re-open when you still experience problems.

Cheers
 eno

**Comment by preimer** [comment]
Hello,

It worked perfectly.  Thanks for the very prompt response!

Paul

--
If you receive this e-mail after hours, during a weekend, or on a holiday,
please enjoy your time off and respond during your working hours.

Paul E Reimer               +1-630-252-4037 (Office)
Bldg 203, Physics Division  +1-630-252-3903 (fax)
Argonne National Laboratory +1-630-344-9207 (mobile)
9700 S Cass Ave             ***@***.******@***.***>
Lemont, IL  60439 USA.      he/his/him

On 7/15/21 10:59, ebothmann wrote:

Hi @preimer<https://github.com/preimer>

The bottle (prebuilt binaries) support is broken in homebrew-hep. I've removed it in the latest commit on master, so if you brew-update, you can re-try and it should work.

I'm tentatively closing this issue, assuming it's resolved. Feel free to re-open when you still experience problems.

Cheers
eno
