### ISSUE TITLE
madgraph5_amcatnlo 

### ISSUE THREAD

**Issue by MarziehB** [davidchall/homebrew-hep#179]
### Indicate troubleshooting steps taken

 - brew install madgraph5_amcatnlo  
the error:
curl: (22) The requested URL returned error: 404 Not Found
Error: madgraph5_amcatnlo: Failed to download resource "madgraph5_amcatnlo"
Download failed: https://launchpad.net/mg5amcnlo/2.0/2.6.x/+download/MG5_aMC_v2.6.5.tar.gz

is it possible to use updated version of madgraph ?

**Comment by ebothmann** [comment]
Hi @MarziehB ... sure; would it be better to upgrade to the latest release (3.2.0) or to the latest in the 2.x series (2.9.5)?

By the way, it's very easy to contribute via pull requests, see "Contributing" at https://github.com/davidchall/homebrew-hep , and in particular bumping a version is very straightforward.

**Comment by MarziehB** [comment]
HI 

I contributed and edit the v2.9.5, however I have problem with ninja package. It fails to install.
./bin/mg5_aMC
> install ninja 
here is the log file
[ninja_install.log](https://github.com/davidchall/homebrew-hep/files/7129915/ninja_install.log)
 thanks

**Comment by ebothmann** [comment]
Sorry I'm not sure what would cause this. I guess the first step would be to check, if this error is actually specific to the installation of MadGraph via homebrew/homebrew-hep. It could also be a (perhaps macOS version specific) bug of MadGraph.

**Comment by davidchall** [comment]
I've updated madgraph5_mcatnlo to v3.3.2 in #215. Could you please try again?
