### ISSUE TITLE
LHAPDF depends on Cython

### ISSUE THREAD

**Issue by truefalsename** [davidchall/homebrew-hep#284]
### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to install lhapdf via homebrew

### What happened (include all command output)?

luca@LMB: ~ > brew install lhapdf
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).

==> Downloading https://lhapdf.hepforge.org/downloads/?f=LHAPDF-6.5.3.tar.gz
Already downloaded: /Users/luca/Library/Caches/Homebrew/downloads/578c1b778b9dbfc28077304780e378f8563d762751010db327e02a15f4005cb0--LHAPDF-6.5.3.tar.gz
==> Installing lhapdf from davidchall/hep
==> Patching
==> ./configure --prefix=/opt/homebrew/Cellar/lhapdf/6.5.3
==> make
Last 15 lines from /Users/luca/Library/Logs/Homebrew/lhapdf/02.make:
  CXXLD    libLHAPDFPaths.la
  CXXLD    libLHAPDFInfo.la
  CXXLD    libLHAPDFGlue.la
  CXXLD    libLHAPDF.la
Making all in include
Making all in LHAPDF
/Library/Developer/CommandLineTools/usr/bin/make  all-am
make[2]: Nothing to be done for `all-am'.
Making all in wrappers
Making all in python
cython ./lhapdf.pyx --cplus -2 -o lhapdf.cpp
make[2]: cython: No such file or directory
make[2]: *** [lhapdf.cpp] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

### What did you expect to happen?

I was expecting that lhapdf installed without errors

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install lhapdf
```

### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
luca@LMB: ~ > brew config
HOMEBREW_VERSION: 3.6.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6e2b162c4786e075323f038d46bfb566d91889e7
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b327cd385a61f4583890a3d12b90789d2a09864d
Core tap last commit: 13 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A
Rosetta 2: false


luca@LMB: ~ > brew doctor
Your system is ready to brew.


luca@LMB: ~ > which cython
/opt/homebrew/bin/cython
```

**Comment by davidchall** [comment]
Hi @truefalsename - unfortunately I'm unable to reproduce this issue on my machine (though I have a very similar setup to you).

Could you please try `brew edit lhapdf` and then adding a code line `depends_on "cython"` next to the python dependency. Hopefully this will unblock you.

**Comment by truefalsename** [comment]
Hello hello, 

that did the trick, thanks!

**Comment by davidchall** [comment]
Happy to hear it! I'll leave this ticket open, in case others encounter this issue. If a few others do, then I'll make the change in the formula.
