### ISSUE TITLE
Failing to install LHAPDF with gcc-12 on M2 MacBook Air

### ISSUE THREAD

**Issue by maus3r** [davidchall/homebrew-hep#285]
### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to install LHAPDF with gcc-12 on a M2 MacBook Air, but I keep getting some kind of segmentation fault.

For this I modified the formula adding the following lines to install:

    # ADD THE FOLLOWING:
    ENV.append "CXXFLAGS", "-stdlib=libstdc++"
    ENV.append "CFLAGS", "-stdlib=libstdc++"
    ENV.append "LDFLAGS", "-stdlib=libstdc++ -lstdc++" 
    # The following is necessary because libtool likes to strip LDFLAGS:  
    ENV["CXX"] = "/opt/homebrew/bin/gcc -stdlib=libstdc++"

### What happened (include all command output)?

The error I am getting looks like this:

ld: warning: directory not found for option '-L/usr/local/opt/libressl/lib'
ld: warning: -undefined dynamic_lookup may not work with chained fixups
0  0x1027141a0  __assert_rtn + 140
1  0x10259ba8c  mach_o::relocatable::Parser<arm64>::parse(mach_o::relocatable::ParserOptions const&) + 4536
2  0x10256dd38  mach_o::relocatable::Parser<arm64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 148
3  0x1025b8180  archive::File<arm64>::makeObjectFileForMember(archive::File<arm64>::Entry const*) const + 1084
4  0x1025b7ac8  archive::File<arm64>::File(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, archive::ParserOptions const&) + 856
5  0x1025b002c  archive::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, archive::ParserOptions const&) + 388
6  0x1025d66d0  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 2016
7  0x1025d9360  ___ZN2ld4tool10InputFilesC2ER7Options_block_invoke + 56
8  0x1b10901f4  _dispatch_client_callout2 + 20
9  0x1b10a3954  _dispatch_apply_invoke + 224
10  0x1b10901b4  _dispatch_client_callout + 20
11  0x1b10a1a04  _dispatch_root_queue_drain + 680
12  0x1b10a2104  _dispatch_worker_thread2 + 164
13  0x1b1250324  _pthread_wqthread + 228
A linker snapshot was created at:
	/tmp/libLHAPDF.dylib-2022-10-07-203831.ld-snapshot
ld: Assertion failed: (_file->_atomsArrayCount == computedAtomCount && "more atoms allocated than expected"), function parse, file macho_relocatable_file.cpp, line 2061.

### What did you expect to happen?

Get an installed version of LHAPDF.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Modify formula to use gcc compiler, adding this to install:

    # ADD THE FOLLOWING:
    ENV.append "CXXFLAGS", "-stdlib=libstdc++"
    ENV.append "CFLAGS", "-stdlib=libstdc++"
    ENV.append "LDFLAGS", "-stdlib=libstdc++ -lstdc++" 
    # The following is necessary because libtool likes to strip LDFLAGS:  
    ENV["CXX"] = "/opt/homebrew/bin/gcc -stdlib=libstdc++"

and run

brew install lhapdf
```

**Comment by maus3r** [comment]
I have resolved the issue in the meanwhile. It is related to a bug introduced in Xcode 14 in the command-line-tools. You can read about it here:

https://stackoverflow.com/questions/73714336/xcode-update-to-version-2395-ld-compile-problem-occurs-computedatomcount-m

and here:

https://github.com/iains/gcc-12-branch/issues/6

The solution is to revert back to Xcode command-line-tools 13.4 as described there.

**Comment by davidchall** [comment]
Marking as "upstream", since this is related to the macOS CLT. Hopefully they can get this sorted - looks like it has many downstream impacts.
