### ISSUE TITLE
Installation of LHAPDF

### ISSUE THREAD

**Issue by jasper7427** [davidchall/homebrew-hep#341]
### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

install lhapdf

### What happened (include all command output)?

Warning: No available formula with the name "lhapdf".
==> Searching for similarly named formulae and casks...
Error: No formulae or casks found for lhapdf.

### What did you expect to happen?

install lhapdf

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
jasper@Jaspers-MacBook-Pro-2 ~ % brew install lhapdf
```

### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
jasper@Jaspers-MacBook-Pro-2 ~ % brew config
HOMEBREW_VERSION: 4.1.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: c0c8a4dd4dd19ec16deb429abd50cdf82ea33b27
Last commit: 3 days ago
Core tap JSON: 17 Oct 20:28 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.0-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false




jasper@Jaspers-MacBook-Pro-2 ~ % brew doctor
Your system is ready to brew.
```

**Comment by davidchall** [comment]
Hi @jasper7427, before installing packages from homebrew-hep, you must first add the tap to your homebrew installation. Did you use `brew tap davidchall/hep`?

**Comment by jasper7427** [comment]
I have now, and that seemed to allow me to install it, I still however get this 
"ModuleNotFoundError: No module named 'lhapdf'' when I try to use it in python.
How do I proceed
Thanks for your help

**Comment by davidchall** [comment]
I think the most likely explanation is that you're using the system installation of Python (i.e., comes with macOS) instead of the Homebrew installation of Python.

Can you try running `which python` so we can see the path to your python executable?

**Comment by jasper7427** [comment]
I have installed python through Homebrew after which running which python3 gave me:
/opt/homebrew/bin/python3

I then tried to import lhapdf directly in terminal after opening python and that didnt work.

Thanks again

**Comment by davidchall** [comment]
Oh, that's very odd. Can you please send the output of `brew test lhapdf`?

**Comment by jasper7427** [comment]
==> Testing davidchall/hep/lhapdf
==> /opt/homebrew/Cellar/lhapdf/6.5.3/bin/lhapdf --help
==> /opt/homebrew/opt/python@3.10/bin/python3.10 -c import lhapdf

**Comment by davidchall** [comment]
This test shows that `import lhapdf` is successful when using the correct Python installation. I suspect you might have multiple Python versions installed (Homebrew supports this), but it's difficult to confirm remotely. 

You can use this full path to execute Python. If you want to be able to simply type "python" then you'd need to edit your PATH environment variable.

**Comment by jasper7427** [comment]
I am currently trying to use it on sublime, after having installed python via homebrew I had to reinstall numpy, scipy etc. to be able to use them on there. Does that not mean that sublime is using this version of python?

Thanks

**Comment by davidchall** [comment]
Sorry, I can't provide support for IDEs. Usually there is some configuration setting to specify your Python environment. I recommend consulting their documentation.

**Comment by jasper7427** [comment]
no problem,
could you explain how to download pdf sets?
Thank you so much

**Comment by ebothmann** [comment]
@davidchall is already putting a lot of time into providing these homebrew packages. In general, this repository is not the right place to ask for instructions on how to use the packages. The exception would be if there are issues which are related to their installation via homebrew(-hep).

Downloading PDF sets is a standard task which is described in the documentation of `lhapdf`.

**Comment by davidchall** [comment]
Thanks, @ebothmann!

@jasper7427 - For context, I left high energy physics many years ago so homebrew-hep maintenance is really a best-effort hobby ("doing my bit for science" 😄). I'm not actually using these packages myself anymore, but I still have some residual knowledge about how they work.

In this case, I refer you to the LHAPDF homepage (https://lhapdf.hepforge.org). They should have documentation about downloading PDF sets there. If not, that would be something you can request with the package maintainers.
