### ISSUE TITLE
Sherpa instalatin 

### ISSUE THREAD

**Issue by OskarSCH** [davidchall/homebrew-hep#38]
I tried to install Sherpa via Homebrew and got the Following response:

"
==> Installing sherpa from davidchall/homebrew-hep
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://www.hepforge.org/archive/sherpa/SHERPA-MC-2.1.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/sherpa-2.1.1.tar.gz
==> Downloading https://sherpa.hepforge.org/trac/raw-attachment/ticket/300/iterator.patch
Already downloaded: /Library/Caches/Homebrew/sherpa--patch-a19e8ee6e788070d3d8e42bdfe72dd5d0271b118.patch
==> Downloading https://sherpa.hepforge.org/trac/raw-attachment/ticket/342/sherpa_OSX_fix.patch
Already downloaded: /Library/Caches/Homebrew/sherpa--patch-3a1754045d755e6cf4e98afc706934992a93aab4.patch
==> Patching
patching file AHADIC++/Tools/Soft_Cluster_Handler.C
patching file AMISIC++/Main/MI_Base.C
patching file ATOOLS/Org/IO_Handler.C
==> ./configure --prefix=/usr/local/Cellar/sherpa/2.1.1 --enable-multithread --enable-hepmc2=/usr/local
cat: /include/sqlite3.h: No such file or directory
./configure: line 21542: test: !=: unary operator expected
configure: WARNING: Cannot find SQLITE_VERSION macro in sqlite3.h header to retrieve SQLite version!
configure: error: Sqlite3 required but not found.
To install a local copy, use the configure option --with-sqlite3=install.
"

I tried uninstalling and reinstalling SQLite but it still didn't work so uninstalled all packages but still the same Error I the edited the Sherpa installation by adding "args << "--with-sqlite3=instal"" and than tried installing sherpa with and without SQLite installed. I also updated brew several times and ran brew doctor.
Can you maybe help me 

ps: these are the packages I successfully installed;

boost		gcc		hepmc		mpfr		readline	xrootd
cloog		gdbm		isl		openssl		rivet		xz
cmake		gmp		lhapdf		pkg-config	root		yaml-cpp
fastjet		gsl		libmpc		python		sqlite		yoda

Best  

Oskar

**Comment by veprbl** [comment]
Could please you try adding ```depends_on "sqlite"``` to your sherpa formula?

**Comment by OskarSCH** [comment]
I still got the same Error after running it. 
But after uninstalling sqlite and running it again I got the following installation report from sqlite:

" ==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.8.8.3.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/sqlite-3.8.8.3.yosemite.bottle.tar.gz
==> Pouring sqlite-3.8.8.3.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

OS X provides an older sqlite3.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/sqlite/lib
    CPPFLAGS: -I/usr/local/opt/sqlite/include

"


and than it stop at the same point.

**Comment by veprbl** [comment]
Then try also adding
```args << "--with-sqlite3=#{Formula['sqlite'].prefix}"```

**Comment by ebothmann** [comment]
This means that sqlite has been correctly installed. It is just printing out a note ("Caveats"). Actually, `depends_on "sqlite"` should do the trick now (try again), as it should generate the build variables mentioned in the Caveats. The question remains why the system-sqlite has not been found before. It is curious that it printed out `cat: /include/sqlite3.h: No such file or directory` ... there is no `include` directory in the root directory. Who points there?

**Comment by veprbl** [comment]
Also worth checking your system's sqlite. What output do you get when you do:
```
ls -la /usr/lib/libsqlite3.dylib /usr/bin/sqlite3 /usr/include/sqlite3*
/usr/bin/sqlite3 --version
sw_vers
```
?

**Comment by OskarSCH** [comment]
so i tried to 'brew update' and than 'brew cleanup' and new I get the error 

/usr/local/Library/Taps/davidchall/homebrew-hep/sherpa.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:135:in `<main>'

**Comment by OskarSCH** [comment]
@veprbl 
I got the out put 

    ls: /usr/include/sqlite3*: No such file or directory
   -rwxr-xr-x  1 root  wheel   143296 18 Sep  2014 /usr/bin/sqlite3
   -rwxr-xr-x  1 root  wheel  4608336 19 Sep  2014 /usr/lib/libsqlite3.dylib
    oskars-MacBook-Air-2:~ oskar$ /usr/bin/sqlite3 --version
    3.8.5 2014-08-15 22:37:57 c8ade949d4a2eb3bba4702a4a0e17b405e9b6ace
    oskars-MacBook-Air-2:~ oskar$ sw_vers
    ProductNam
    -rwxr-xr-x  1 root  wheel  4608336 19 Sep  2014 /usr/lib/libsqlite3.dylib
    oskars-MacBook-Air-2:~ oskar$ /usr/bin/sqlite3 --version
    3.8.5 2014-08-15 22:37:57 c8ade949d4a2eb3bba4702a4a0e17b405e9b6ace
    oskars-MacBook-Air-2:~ oskar$ sw_vers
    ProductName:	Mac OS X
    ProductVersion:	10.10.2
    BuildVersion:	14C1510e:	Mac OS X
    ProductVersion:	10.10.2
    BuildVersion:	14C1510

**Comment by ebothmann** [comment]
no wonder it doesn't find the system headers .. they are clearly absent
did you ever meddle with your `/usr/include` directory?

**Comment by OskarSCH** [comment]
no I didn't meddle my directory and  "usr/local/bin" is also inoculate

**Comment by veprbl** [comment]
@OskarSCH 
Make sure that you have have some incorrect edits in your sherpa formula. What I've proposed looked like:
```patch
diff --git a/sherpa.rb b/sherpa.rb
index 3827894..ea05e5d 100644
--- a/sherpa.rb
+++ b/sherpa.rb
@@ -16,6 +16,7 @@ class Sherpa < Formula
     sha1 '3a1754045d755e6cf4e98afc706934992a93aab4'
   end
 
+  depends_on "sqlite"
   depends_on 'hepmc'   => :recommended
   depends_on 'rivet'   => :recommended
   depends_on 'lhapdf'  => :recommended
@@ -46,6 +47,7 @@ class Sherpa < Formula
       ENV['FC'] = ENV['MPIFC']
     end
 
+    args << "--with-sqlite3=#{Formula['sqlite'].prefix}"
     args << "--enable-hepmc2=#{Formula['hepmc'].prefix}"    if build.with? "hepmc"
     args << "--enable-rivet=#{Formula['rivet'].prefix}"     if build.with? "rivet"
     args << "--enable-lhapdf=#{Formula['lhapdf'].prefix}"   if build.with? "lhapdf"
```
This should allow you to build Sherpa with sqlite from homebrew.

Also, I agree with @ebothmann . It may be that something is not right with your system.

**Comment by ebothmann** [comment]
Does anyone know if sqlite is installed with the command line tools (CLT) or during system install? If the former is the case, a reinstall of the CLT might help. A quick web search didn't help much ...

**Comment by veprbl** [comment]
@OskarSCH
Do you use full Xcode or just Command Line Tools?
Could you also tell us what is the output of
```
find /Library /usr -name "sqlite*.h"
```

**Comment by OskarSCH** [comment]
/usr/local/Cellar/sqlite/3.8.8.3/include/sqlite3.h
    /usr/local/Cellar/sqlite/3.8.8.3/include/sqlite3ext.h

I'm using Xcode and have the most recent version.

**Comment by veprbl** [comment]
Also check if you have Mac OS X SDK (downloads available somewhere in XCode settings).

If it's all right, then see if you have header in there
```
find /Applications/Xcode.app/ -name "sqlite*.h"
```
Full path to it should be something like ```/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/sqlite3.h```

**Comment by OskarSCH** [comment]
I downloaded OS X and my path looks the same.

but i still get the error i got in the beginning with out     args << "--with-sqlite3=#{Formula["sqlite"].perfix}" 


and with i get 


    /usr/local/Library/Taps/davidchall/homebrew-hep/sherpa.rb:53:in `install'
/usr/local/Library/Homebrew/build.rb:136:in `block in install'
    /usr/local/Library/Homebrew/formula.rb:410:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:766:in `block in stage'
    /usr/local/Library/Homebrew/resource.rb:91:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
    /usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
    /usr/local/Library/Homebrew/formula.rb:764:in `stage'
/usr/local/Library/Homebrew/formula.rb:406:in `brew'
     /usr/local/Library/Homebrew/build.rb:114:in `install'
/usr/local/Library/Homebrew/build.rb:185:in `<main>'

**Comment by veprbl** [comment]
@OskarSCH 
To revert the changes you did to the formula do:
```
cd /usr/local/Library/Taps/davidchall/homebrew-hep/
git reset --hard HEAD
```

**Comment by OskarSCH** [comment]
no I simply added #

**Comment by veprbl** [comment]
There must be some change that broke the formula. To see your changes do:
```
cd /usr/local/Library/Taps/davidchall/homebrew-hep/
git diff
```

**Comment by OskarSCH** [comment]
I reverted all the changes and inserted the editions again, and now he is     "make install" 
so maybe it finally is working

**Comment by OskarSCH** [comment]
i worked thank you

**Comment by veprbl** [comment]
So you've downloaded SDK? Do you now have ```/usr/include/sqlite3.h```?

**Comment by davidchall** [comment]
I'm unclear whether this requires any action?

**Comment by ebothmann** [comment]
I don't think so. Usually the system sqlite is found afaik.

**Comment by davidchall** [comment]
Ok, I'm closing this then
