### ISSUE TITLE
Problems Installing LHAPDF

### ISSUE THREAD

**Issue by fliptanedo** [davidchall/homebrew-hep#39]
Hello, I'm having trouble installing LHAPDF through homebrew-hep. I've run `brew update'.

Here's the gist: https://gist.github.com/9b67ca7df8a61bfeb1f9

    $ brew install lhapdf
    ==> Installing lhapdf from davidchall/homebrew-hep
    ==> Installing lhapdf dependency: boost
    ==> Downloading https://homebrew.bintray.com/bottles/boost-1.57.0.yosemite.bottl
    ######################################################################## 100.0%
    ==> Pouring boost-1.57.0.yosemite.bottle.tar.gz
    🍺  /usr/local/Cellar/boost/1.57.0: 10572 files, 439M
    ==> Installing lhapdf
    ==> Downloading http://www.hepforge.org/archive/lhapdf/LHAPDF-6.1.4.tar.gz
    Already downloaded: /Library/Caches/Homebrew/lhapdf-6.1.4.tar.gz
    ==> ./configure --prefix=/usr/local/Cellar/lhapdf/6.1.4 --with-boost=/usr/local/
    checking for Boost's header version... 1_57
    checking boost/foreach.hpp usability... no
    checking boost/foreach.hpp presence... no
    checking for boost/foreach.hpp... no
    configure: error: cannot find boost/foreach.hpp
    
    READ THIS: https://git.io/brew-troubleshooting
    If reporting this issue please do so at (not Homebrew/homebrew):
      https://github.com/davidchall/homebrew-hep/issues/
    
## Possible sources of complication:
I've installed Anaconda (Continuum analytics) for Python and get the following when I run `brew doctor`

    $ brew doctor
    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!
    
    Warning: "config" scripts exist outside your system or Homebrew directories.
    `./configure` scripts often look for *-config scripts to determine if
    software packages are installed, and what additional flags to use when
    compiling and linking.
    
    Having additional scripts in your path can confuse software installed via
    Homebrew if the config script overrides a system or Homebrew provided
    script of the same name. We found the following "config" scripts:
    
      /Users/fliptanedo/anaconda/bin/curl-config
      /Users/fliptanedo/anaconda/bin/freetype-config
      /Users/fliptanedo/anaconda/bin/libdynd-config
      /Users/fliptanedo/anaconda/bin/libpng-config
      /Users/fliptanedo/anaconda/bin/libpng15-config
      /Users/fliptanedo/anaconda/bin/llvm-config
      /Users/fliptanedo/anaconda/bin/python-config
      /Users/fliptanedo/anaconda/bin/python2-config
      /Users/fliptanedo/anaconda/bin/python2.7-config
      /Users/fliptanedo/anaconda/bin/xml2-config
      /Users/fliptanedo/anaconda/bin/xslt-config

**Comment by fliptanedo** [comment]
For what it's worth, the file `foreach.hpp' is available in `/usr/local/Cellar/boost/1.57.0/include/boost'. Here's the `ls -l foreach.hpp`:

    -rw-r--r--  1 fliptanedo  admin    44K Dec 18 01:39 foreach.hpp

**Comment by veprbl** [comment]
From your config.log:
```
configure:16494: checking boost/foreach.hpp presence
configure:16494: clang++ -E  -I/usr/local/Cellar/lhapdf/6.1.4/include -I/usr/local/Cellar/boost/1.57.0/include conftest.cpp
In file included from conftest.cpp:28:
In file included from /usr/local/Cellar/boost/1.57.0/include/boost/foreach.hpp:73:
In file included from /usr/local/Cellar/boost/1.57.0/include/boost/range/end.hpp:25:
In file included from /usr/local/Cellar/boost/1.57.0/include/boost/range/iterator.hpp:20:
In file included from /usr/local/Cellar/boost/1.57.0/include/boost/range/mutable_iterator.hpp:23:
In file included from /usr/local/Cellar/boost/1.57.0/include/boost/iterator/iterator_traits.hpp:8:
In file included from /usr/local/Cellar/boost/1.57.0/include/boost/detail/iterator.hpp:11:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found
#include <__debug>
         ^
1 error generated.
```
This seems to be a fresh bug in Apple's CLT:
http://stackoverflow.com/questions/29529455/missing-c-header-debug-after-updating-osx-command-line-tools-6-3

**Comment by fliptanedo** [comment]
Thanks, @veprbl . Following the link posted, I downgraded to CLT 6.2 and I'm now able to install lhapdf from homebrew-hep.

However, I seem to still have problems loading lhapdf. When I try to import lhapdf from Python I get an error. I import lhadf as follows:

```Python
# Import LHAPDF from Homebrew directory
import sys
FlipPath='/usr/local/Cellar/lhapdf/6.1.5/lib/python2.7/site-packages'
sys.path.append(FlipPath)
import lhapdf
```
I get the following error:

```Python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-ffeb5e0e6bb3> in <module>()
     12 FlipPath='/usr/local/Cellar/lhapdf/6.1.5/lib/python2.7/site-packages'
     13 sys.path.append(FlipPath)
---> 14 import lhapdf

ImportError: dlopen(/usr/local/Cellar/lhapdf/6.1.5/lib/python2.7/site-packages/lhapdf.so, 2): Symbol not found: __ZN6LHAPDF4Info4loadERKSs
  Referenced from: /usr/local/Cellar/lhapdf/6.1.5/lib/python2.7/site-packages/lhapdf.so
  Expected in: dynamic lookup
```

Might there be any suggestions for this?

Thanks very much!

**Comment by veprbl** [comment]
Could you please show your output for the following command:
```
otool -L /usr/local/Cellar/lhapdf/6.1.5/lib/python2.7/site-packages/lhapdf.so
```

**Comment by fliptanedo** [comment]
Here's the output:
```
/usr/local/Cellar/lhapdf/6.1.5/lib/python2.7/site-packages/lhapdf.so:
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
	/usr/local/Cellar/lhapdf/6.1.5/lib/libLHAPDF.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 283.0.0)
```

**Comment by veprbl** [comment]
Your output looks ok.
Are you using brewed python?
Because I am and ```import lhapdf``` works for me without the modification of sys.path.

It seems like the problem is with anaconda. Symbol ```__ZN6LHAPDF4Info4loadERKSs``` is a mangled name for ```LHAPDF::Info::load(std::string const&)```. When I check my libLHAPDF.dylib I see a completely different signature:
```
# otool -tv /usr/local/Cellar/lhapdf/6.1.5/lib/libLHAPDF.dylib | grep __ZN6LHAPDF4Info4load | c++filt
LHAPDF::Info::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&):
```
This can be caused by wrong compiler options picked up from ```/Users/fliptanedo/anaconda/bin/python*-config```.

**Comment by veprbl** [comment]
It is likely that the output of
```
/Users/fliptanedo/anaconda/bin/python-config --cflags --ldflags --libs
```
contains ```-stdlib=libstdc++```.

**Comment by fliptanedo** [comment]
Ah, I was hoping something like this wouldn't be the case.

I tried commenting out Anaconda from my path in my `.bash_profile`: 

```
fliptanedo$ cat ~/.bash_profile 
# added by Anaconda 2.1.0 installer
# export PATH="/Users/fliptanedo/anaconda/bin:$PATH"
```

And then tried again in the Python interpreter (after starting a new terminal):

```Python
>>> import sys
>>> print sys.path
['', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages']
>>> import lhapdf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named lhapdf
>>> import sys
>>> FlipPath='/usr/local/Cellar/lhapdf/6.1.5/lib/python2.7/site-packages'
>>> sys.path.append(FlipPath)
>>> import lhapdf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/usr/local/Cellar/lhapdf/6.1.5/lib/python2.7/site-packages/lhapdf.so, 2): Symbol not found: __ZN6LHAPDF4Info4loadERKSs
  Referenced from: /usr/local/Cellar/lhapdf/6.1.5/lib/python2.7/site-packages/lhapdf.so
  Expected in: dynamic lookup
```
As you can see from the path, it's no longer looking for Anaconda. But I suppose the config files may still be confusing the system?

Here's my status:
1. I have commented out Anacoda from my `.bash_profile` so that Anaconda is no longer being exported into my path. However, I haven't deleted any Anaconda files. 

2. I have not installed Python through Homebrew. (e.g. see the path output above)

3. I'm still getting the `Symbol not found: __ZN6LHAPDF4Info4loadERKSs` import error, which you've explained is likely to be from Anaconda's config. 


What should my next step be? (Apologies that I'm not so familiar with these sorts of things.) Now that Anaconda is not being added to my path, may I safely ignore it and just install Python from Homebrew? Or do I need to do a more extensive uninstall of Anaconda?

Thanks so much for your help on this.

**Comment by veprbl** [comment]
Anaconda is built against libstdc++ whereas modern OSX and Homebrew use libc++ as a standard. You can not use libraries linked with libstdc++ from libc++ software and vice versa.

LHAPDF is actually a two libraries. One of them is the actual LHAPDF library (libLHAPDF.dylib) and it is built with default libc++ stdlib. The other is an interface to python (lhapdf.so) and it happens to pick up settings from your current python. Your current python is the one shipped with anaconda and it's built against libstdc++ (probably for compatibility with older OSX versions).

Possible options are:
1. to not use anaconda (remove anaconda paths from environment and ```brew reinstall lhapdf```)
2. to ask anaconda developers for binaries built against libc++
3. to build lhapdf and it's dependencies fully against libstdc++ (the hard way)

Later case seems to be plausible according to https://haduonght.wordpress.com/2015/02/21/install-caffe-on-mac-os-x-10-10/
You (probably) will need to do only two steps:

1) ```brew edit lhapdf``` and ```brew edit boost``` and do a following modification:
```patch
def install
+    # ADD THE FOLLOWING:
+    ENV.append "CXXFLAGS", "-stdlib=libstdc++"
+    ENV.append "CFLAGS", "-stdlib=libstdc++"
+    ENV.append "LDFLAGS", "-stdlib=libstdc++ -lstdc++"
+    # The following is necessary because libtool likes to strip LDFLAGS:
+    ENV["CXX"] = "/usr/bin/clang++ -stdlib=libstdc++"
```
You may also need to downgrade your boost:
```patch
   homepage "http://www.boost.org"
-  url "https://downloads.sourceforge.net/project/boost/boost/1.56.0/boost_1_56_0.tar.bz2"
-  sha1 "f94bb008900ed5ba1994a1072140590784b9b5df"
+  url 'https://downloads.sourceforge.net/project/boost/boost/1.55.0/boost_1_55_0.tar.bz2'
+  sha1 'cef9a0cc7084b1d639e06cd3bc34e4251524c840'
+  revision 2
   head "https://github.com/boostorg/boost.git"
```
2) ```brew uninstall boost```, ```brew uninstall lhapdf``` and ```brew install --build-from-source boost```, ```brew install --build-from-source lhapdf```

**Comment by veprbl** [comment]
@fliptanedo could you provide ```brew gist-logs lhapdf``` for build with anaconda?

**Comment by fliptanedo** [comment]
Thanks @veprbl ; I really appreciate the explanations of what's going on. If I understand correctly: I can go ahead and leave Anaconda out of my path (by commenting it out of of my `.bash_profile`) and follow your option 1 (don't use Anaconda, do `brew reinstall lhapdf`). I can now delete the Anaconda directory or leave it in case I want to use it again by adding it to my path?

I also appreciate the more detailed instructions for making lhapdf robust against libstdc++; I don't think I'll go this route, but I hope it'll be useful for others in the same situation. (If so, I hope they can post to let us know how it works.)

**Comment by fliptanedo** [comment]
> @fliptanedo could you provide brew gist-logs lhapdf for build with anaconda?

[https://gist.github.com/27d847e9ee4104040041] (https://gist.github.com/27d847e9ee4104040041)

Here's the output (just to make sure that I still had Anaconda in my `$PATH` when I ran `brew gist-logs`):
```
fliptanedo$ echo $PATH
/Users/fliptanedo/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/texbin
fliptanedo$ brew gist-logs lhapdf
https://gist.github.com/27d847e9ee4104040041
```

Thanks again for all of your help. I'll try to reinstall `lhapdf` later today and will close the issue if it works.

**Comment by fliptanedo** [comment]
Hello---I've followed the advice of @veprbl (option 1 [here](https://github.com/davidchall/homebrew-hep/issues/39#issuecomment-94304623)) and have done the following:

1. Modified my `~/.bash_profile` so that the line exporting the Anaconda directory to `$PATH` is now commented out:
```
# added by Anaconda 2.1.0 installer
# export PATH="/Users/fliptanedo/anaconda/bin:$PATH"
```
(I'll note for novices like me that one has to open a new terminal window for this change to take effect.) At this point one may delete the Anaconda directory completely.
2. Installed Python through Homebrew, `brew install python`.
3. Re-installed lhapdf using `brew reinstall lhapdf`

This now works: I was able to call `import lhapdf` from the Python interpreter without any problems and without having to point to the lhapdf directory.

Thanks, @veprbl for all of the help!

**Comment by veprbl** [comment]
Yesterday I've realised that CPython (the python interpreter) doesn't have any C++ API so it's not linked to any C++ library at all. This makes lhapdf.so the only piece that is wrongly linked to stdlibc++. So option four would be to fix this somehow.

Looking at the log provided by @fliptanedo 
```
clang called with: -fno-strict-aliasing -I/Users/fliptanedo/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/private/tmp/lhapdf20150415-12218-1fyxpbo/LHAPDF-6.1.5/include -I/private/tmp/lhapdf20150415-12218-1fyxpbo/LHAPDF-6.1.5/include -I/Users/fliptanedo/anaconda/include/python2.7 -c lhapdf.cpp -o build/temp.macosx-10.5-x86_64-2.7/lhapdf.o -I/usr/local/Cellar/boost/1.57.0/include -I/usr/local/Cellar/lhapdf/6.1.5/include
superenv removed:  -arch x86_64 -g -O3 -Wall -Wstrict-prototypes
superenv added:    -pipe -w -Os -march=native -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=native -fno-strict-aliasing -I/Users/fliptanedo/anaconda/include -DNDEBUG -fwrapv -I/private/tmp/lhapdf20150415-12218-1fyxpbo/LHAPDF-6.1.5/include -I/Users/fliptanedo/anaconda/include/python2.7 -c lhapdf.cpp -o build/temp.macosx-10.5-x86_64-2.7/lhapdf.o -I/usr/local/Cellar/boost/1.57.0/include -I/usr/local/Cellar/lhapdf/6.1.5/include -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
 
clang called with: -bundle -undefined dynamic_lookup -L/Users/fliptanedo/anaconda/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.5-x86_64-2.7/lhapdf.o -L/private/tmp/lhapdf20150415-12218-1fyxpbo/LHAPDF-6.1.5/src/.libs -L/Users/fliptanedo/anaconda/lib -lstdc++ -lLHAPDF -o build/lib.macosx-10.5-x86_64-2.7/lhapdf.so
superenv removed:  -arch x86_64 -arch x86_64
superenv added:    -pipe -w -Os -march=native -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -w -Os -march=native -bundle -undefined dynamic_lookup -L/Users/fliptanedo/anaconda/lib build/temp.macosx-10.5-x86_64-2.7/lhapdf.o -L/private/tmp/lhapdf20150415-12218-1fyxpbo/LHAPDF-6.1.5/src/.libs -lstdc++ -lLHAPDF -o build/lib.macosx-10.5-x86_64-2.7/lhapdf.so -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
```
I don't see any suspicious difference to a "healthy" log:
```
clang called with: -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/private/tmp/lhapdf20150420-32735-1px5yva/LHAPDF-6.1.5/include -I/private/tmp/lhapdf20150420-32735-1px5yva/LHAPDF-6.1.5/include -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c lhapdf.cpp -o build/temp.macosx-10.10-x86_64-2.7/lhapdf.o -I/usr/local/Cellar/boost/1.57.0/include -I/usr/local/Cellar/lhapdf/6.1.5/include
superenv removed:  -I/usr/local/include -g -O3 -Wall -Wstrict-prototypes
superenv added:    -pipe -w -Os -march=native -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=native -fno-strict-aliasing -fno-common -dynamic -I/usr/local/opt/sqlite/include -DNDEBUG -fwrapv -I/private/tmp/lhapdf20150420-32735-1px5yva/LHAPDF-6.1.5/include -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c lhapdf.cpp -o build/temp.macosx-10.10-x86_64-2.7/lhapdf.o -I/usr/local/Cellar/boost/1.57.0/include -I/usr/local/Cellar/lhapdf/6.1.5/include -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
 
clang called with: -bundle -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/sqlite/lib build/temp.macosx-10.10-x86_64-2.7/lhapdf.o -L/private/tmp/lhapdf20150420-32735-1px5yva/LHAPDF-6.1.5/src/.libs -lstdc++ -lLHAPDF -o build/lib.macosx-10.10-x86_64-2.7/lhapdf.so
superenv added:    -pipe -w -Os -march=native -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -w -Os -march=native -bundle -undefined dynamic_lookup -L/usr/local/opt/sqlite/lib build/temp.macosx-10.10-x86_64-2.7/lhapdf.o -L/private/tmp/lhapdf20150420-32735-1px5yva/LHAPDF-6.1.5/src/.libs -lstdc++ -lLHAPDF -o build/lib.macosx-10.10-x86_64-2.7/lhapdf.so -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
```
I don't understand where things go wrong here.

@fliptanedo Glad this works for you now.
