### ISSUE TITLE
Problem upgrading Pythia package to 8.205

### ISSUE THREAD

**Issue by amsimone** [davidchall/homebrew-hep#40]
Dear David,
I have tried to upgrade the Pythia8 package from 8.186 to 8.205.
I updated the tar file and the SHA1 key, and the installation seem successful.
The file also  seem to all be in the correct location,
however if I try doing pythia8-config it does not work.
Am I missing any step? Or would you know what might have gone wrong?
Simone

**Comment by davidchall** [comment]
We have Pythia 8.125 now, so I'm closing this. But of course, let me know if you have any problems with this new version.
