### ISSUE TITLE
Rivet 3.1.10 and Hepmc3 3.3.0

### ISSUE THREAD

**Issue by siddharthsule** [davidchall/homebrew-hep#404]
### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I recently did a `brew upgrade`; now rivet doesn't seem to work.

### What happened (include all command output)?

I tried to run the command `rivet` and I got the following error

```
The rivet Python module could not be loaded: are your PYTHONPATH and (DY)LD_LIBRARY_PATH set correctly?
Try running 'python -c "import rivet"' at the command line (or "import rivet" in a Python REPL)
Full error message:
dlopen(/opt/homebrew/lib/python3.10/site-packages/rivet/core.so, 0x000A): Library not loaded: /opt/homebrew/opt/hepmc3/lib/libHepMC3.3.dylib
  Referenced from: <0382DA4F-BAA4-3580-A55B-109197089B77> /opt/homebrew/Cellar/rivet/3.1.10/lib/python3.10/site-packages/rivet/core.so
  Reason: tried: '/opt/homebrew/opt/hepmc3/lib/libHepMC3.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/hepmc3/lib/libHepMC3.3.dylib' (no such file), '/opt/homebrew/opt/hepmc3/lib/libHepMC3.3.dylib' (no such file), '/opt/homebrew/Cellar/hepmc3/3.3.0/lib/libHepMC3.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/hepmc3/3.3.0/lib/libHepMC3.3.dylib' (no such file), '/opt/homebrew/Cellar/hepmc3/3.3.0/lib/libHepMC3.3.dylib' (no such file)
```

I checked my python install (also via homebrew) and reinstalled rivet, yoda, hepmc3 and fastjet

I then did `ls /opt/homebrew/opt/hepmc3/lib/` but the file `libHepMC3.3.dylib` doesn't seem to be there, but there is a `libHepMC3.4.dylib` instead.

### What did you expect to happen?

Everthing to run as per (might be a versioning issue?)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew uninstall rivet yoda hepmc fastjet
brew install rivet
rivet
```

**Comment by davidchall** [comment]
Hi @siddharthsule - It appears HepMC 3.3.0 has some breaking changes that require a new version of Rivet. Until downstream dependencies are ready, I've reverted HepMC to the previous version. Please uninstall and try again. Thanks for the report!
