### ISSUE TITLE
problem upgrading sherpa 2.1.1 to 2.2.0

### ISSUE THREAD

**Issue by ahmedqamesh** [davidchall/homebrew-hep#49]
/var/folders/zb/nm26p2gx6m53v9pqz4xjf8m80000gn/T//cc6f1S6l.s:2554:suffix or operands invalid for `movq'
/var/folders/zb/nm26p2gx6m53v9pqz4xjf8m80000gn/T//cc6f1S6l.s:2555:suffix or operands invalid for `movq'
/var/folders/zb/nm26p2gx6m53v9pqz4xjf8m80000gn/T//cc6f1S6l.s:2589:suffix or operands invalid for `movq'
/var/folders/zb/nm26p2gx6m53v9pqz4xjf8m80000gn/T//cc6f1S6l.s:2590:suffix or operands invalid for `movq'
make[2]: *** [CT12Pdf.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/davidchall/homebrew-hep/issues

**Comment by veprbl** [comment]
Please run ```brew gist-logs sherpa``` and post the result here.

**Comment by ahmedqamesh** [comment]
rhis is what appers to me
https://gist.github.com/386b43927b78a6826d30
________________________________

**Comment by veprbl** [comment]
Try updating to the latest version of Command Line Tools first. You can them from (https://developer.apple.com/downloads/).
If that is undesirable or doesn't help, try to rebuild your gcc in your system's environment (```brew reinstall --build-from-source gcc```, it will take some cpu time to do this)

**Comment by ahmedqamesh** [comment]
thank u
i am downloading the update right now
I have another question related to the libraries
, for example I want to link Shepa with MCFM and PDF
I unix I was following these steps
./configure --prefix=/usr/local/sherpa143 --enable-lhapdf=/usr/local/lhapdf-5.7.0  -enable-mcfm=/usr/local/Cellar/sherpa/2.1.1/include/SHERPA-MC/AddOns/MCFM
but now , I don't know where the configure file is  hiding.
I mean how can I add new libraries to the sherpa itself on Mac
Regards
________________________________

**Comment by veprbl** [comment]
If you want your sherpa with MCFM support use ```brew install --with-mcfm sherpa```. To see the list of other possible options use ```brew info sherpa```. To see how homebrew formula interacts with configure script see ```brew edit sherpa```.

**Comment by davidchall** [comment]
Thanks @veprbl for answering Ahmed's questions. I think this is now closed.
