### ISSUE TITLE
Could not find Pythia 8 library and headers

### ISSUE THREAD

**Issue by apctranque** [davidchall/homebrew-hep#62]
Hello,
I installed Pythia 8 by `brew install pythia8` then  I continued installing `brew install sacrifice` to generate Pythia 8 events. However, there is an configure error: Could not find Pythia 8 library and headers!! . Could you guys help me to solve it? Thanks
<img width="654" alt="screen shot 2016-03-21 at 5 35 05 pm" src="https://cloud.githubusercontent.com/assets/17979231/13914738/4c7758cc-ef8b-11e5-8480-9a47b32b6501.png">

**Comment by davidchall** [comment]
Unfortunately, the latest release of Sacrifice does not support the latest version of Pythia8. This means that you need to install Sacrifice directly using this source repository. This can be achieved with

    brew install sacrifice --HEAD

**Comment by apctranque** [comment]
It worked! 
Thanks a lot David!
