### ISSUE TITLE
mcgrid fails with latest rivet

### ISSUE THREAD

**Issue by davidchall** [davidchall/homebrew-hep#71]
I know that @nhartland and @ebothmann are both interested in this package.

MCgrid fails when building against Rivet-2.5.0 because Rivet now relies upon C++11 and has removed the Boost library dependency. I think that MCgrid will either need to explicitly use Boost (rather than via Rivet) or will need to update to C++11.

**Comment by nhartland** [comment]
Thanks for pointing this out, we'll get this fixed ASAP.

**Comment by davidchall** [comment]
Fixed by https://github.com/davidchall/homebrew-hep/commit/7aaad4d82ae8024bad3549c0b1e179017c82ebc5
