### ISSUE TITLE
Seg Fault 11 in rivet

### ISSUE THREAD

**Issue by cjohnson-phys** [davidchall/homebrew-hep#76]
When I run "rivet --list-analyses", i run into a Seg Fault.
Can someone verify that they are also seeing this (when rivet is built against clang)?

Alex

**Comment by veprbl** [comment]
Works for me on brewed 2.5.0

**Comment by cjohnson-phys** [comment]
Even with it built against clang!

**Comment by cjohnson-phys** [comment]
I even uninstalled everything in homebrew to start clean. Then used the
rivet-bootstrap to install it and it still gave the same error.

**Comment by veprbl** [comment]
Apple clang, yes:
```
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by cjohnson-phys** [comment]
Hmmm, the only difference is that I am using x86_64-apple-darwin15.5.0...

**Comment by veprbl** [comment]
Can you get a stack trace?

**Comment by veprbl** [comment]
Try
```python -c 'import rivet; print rivet.AnalysisLoader.analysisNames()'```

**Comment by cjohnson-phys** [comment]
Looked through the report, apparently it did not like one of the several analyses that I add to the RIVET_ANALYSIS_PATH.

I feel dumb, lol. Thanks for the help! I'll check what Rivet 2.5.0 doesn't like about this particular analysis and get back to you.
