### ISSUE TITLE
Sherpa --with-rivet problems

### ISSUE THREAD

**Issue by nhartland** [davidchall/homebrew-hep#79]
I'm getting the following error when installing Sherpa 2.1.1 from the new formula, including the --with-rivet option

> → brew install Sherpa --with-rivet               
> ==> Installing sherpa from davidchall/hep
> ==> Using Homebrew-provided fortran compiler.
> This may be changed by setting the FC environment variable.
> ==> Downloading http://www.hepforge.org/archive/sherpa/SHERPA-MC-2.2.1.tar.gz
> Already downloaded: /Users/hartland/Library/Caches/Homebrew/sherpa-2.2.1.tar.gz
> ==> ./configure --prefix=/usr/local/Cellar/sherpa/2.2.1 --enable-hepmc2=/usr/local/opt/hepmc --enable-rivet=/usr/local/opt/rivet --enable-lhapdf=/usr/local/opt/lhapdf
> ==> make install
> Last 15 lines from /Users/hartland/Library/Logs/Homebrew/sherpa/02.make:
> make_shared(_A0& __a0, _A1& __a1, _A2& __a2)
> ^
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:4769:1: note: candidate function template not viable: requires 0 arguments, but 3 were provided
> make_shared()
> ^
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:4777:1: note: candidate function template not viable: requires single argument '__a0', but 3 arguments were provided
> make_shared(_A0& __a0)
> ^
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:4785:1: note: candidate function template not viable: requires 2 arguments, but 3 were provided
> make_shared(_A0& __a0, _A1& __a1)
> ^
> 6 errors generated.
> make[2]: *** [libSherpaRivetAnalysis_la-Rivet_Interface.lo] Error 1
> make[1]: *** [install-recursive] Error 1
> make: *** [install-recursive] Error 1

Is anyone else seeing a similar problem?

**Comment by ebothmann** [comment]
Hi Nathan,

I have fixed this already and will make the pull request in a few minutes.

Cheers,
 eno

**Comment by davidchall** [comment]
Hi Nathan, I've accepted the fix. I'm closing this, but please reopen if it doesn't work for you.
