### ISSUE TITLE
Warning from UGS

### ISSUE THREAD

**Issue by haggerty** [davidchall/homebrew-hep#83]
I started getting these warnings a few weeks ago every time I brew upgrade or cleanup:

[~]$ brew upgrade
Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/davidchall/homebrew-hep/ugs.rb:14:in `block in <class:Ugs>'
Please report this to the davidchall/hep tap!
...repeated 3 times

It doesn't have any bad effect, but the warning clutters up the brewing.

Incidentally, this tap is a great contribution and very useful, thanks for the work that goes into it!

**Comment by davidchall** [comment]
Thanks for the report -- this should be fixed the next time you `brew update`.

Glad to hear that `homebrew-hep` is helping you. Please considering "starring" the repo and sharing with your Mac-friendly colleagues 👍
