### ISSUE TITLE
Brew upgrade error

### ISSUE THREAD

**Issue by debtosh** [davidchall/homebrew-hep#89]
Hi David,

After updating brew today, if I try to brew upgrade I'm getting the following error:

dhwired13098:~ debtosh$ brew outdated
Error: /usr/local/Homebrew/Library/Taps/davidchall/homebrew-hep/fjcontrib.rb:7: syntax error, unexpected tIDENTIFIER, expecting keyword_end
  option "with-test", "Test during installation"
              ^
/usr/local/Homebrew/Library/Taps/davidchall/homebrew-hep/fjcontrib.rb:7: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
  option "with-test", "Test during installation"
                    ^
/usr/local/Homebrew/Library/Taps/davidchall/homebrew-hep/fjcontrib.rb:7: syntax error, unexpected tCONSTANT, expecting keyword_end
  option "with-test", "Test during installation"
                           ^
/usr/local/Homebrew/Library/Taps/davidchall/homebrew-hep/fjcontrib.rb:9: syntax error, unexpected tIDENTIFIER, expecting keyword_end
  depends_on "fastjet"
                     ^
/usr/local/Homebrew/Library/Taps/davidchall/homebrew-hep/fjcontrib.rb:13: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
    system "make"
            ^
/usr/local/Homebrew/Library/Taps/davidchall/homebrew-hep/fjcontrib.rb:17: syntax error, unexpected keyword_end, expecting end-of-input

As you can see, all the errors are pointing to fjcontrib.rb file. I see that fastjet, fjcontrib,rivet, and yoda got updated. Any help regarding this will be highly appreciated.

Cheers,
Debtosh

**Comment by davidchall** [comment]
I apologize - the continuous integration doesn't seem to work at the moment, so I accepted those changes without really testing.

I've just fixed the bug though, so it should work fine again.

**Comment by debtosh** [comment]
Hi David,
Thanks for solving the issue.
